getmyhead:
  # Время в секундах, перед повторным использованием команды
  cooldown: 3
  damage: 1
  effects:
    enabled: true
    # Эффекты которые выдаются при выдачи головы
    list: # Название эффекта : Время(В секундах) : Уровень эффекта (Ознакомьтесь на вики по вашей версии PotionEffectType.class)
      - "BLINDNESS:60:2"
      - "SLOW:60:2"

followme:
  # Время в секундах, перед повторным использованием команды
  cooldown: 3
  # Данная функция активирует свечение лидера для всех подписчиков
  # Доступно с 1.9+
  glowing: true
  # Расстояние вызвавшего команду `followme` до ближайших игроков,
  # чтобы сделать их последователями
  radius: 50
  # Урон в секунду(Как пример в конфиге каждые 5 блоков мы наносим урон равный 1)
  damage-radius: 5
  damage: 1
  effects:
    enabled: true
    # Каждые сколько блоков будут усиливаться эффекты
    amplifier-radius: 20
    list: # Название эффектов (Ознакомьтесь на вики по вашей версии PotionEffectType.class)
      - "INCREASE_DAMAGE"
      - "SPEED"

messages:
  followme: " &8| &7Вы стали последователем игрока %playername%"
  damageradius:  " &8| &7Вы находитесь далеко от своего лидера, пришло время наказать вас!"
  cooldown: " &8| &7Не используйте так часто команду!"
  notenoughplayers: " &8| &7Рядом с вами нету игроков"
