# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17.0.2+8
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '17.0.2+8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path:  |
            ./target/GravitTestTaskMaven*.jar
      - name: get version and date
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}_${{ env.date }}
          fail_on_unmatched_files: true
          files: "./target/GravitTestTaskMaven*.jar"
          draft: false
          prerelease: false
